name: Dozer
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
targets:
  Dozer:
    type: application
    platform: macOS
    deploymentTarget: "10.12"
    sources:
      - Dozer
    postbuildScripts:
      - path: LaunchAtLogin.sh
        name: LaunchAtLogin
      - path: Scripts/Unused.sh
        name: Unused
      - path: Scripts/LinkFabric.sh
        name: LinkFabric
    settings:
      DEVELOPMENT_TEAM: DE6MHLRTVN
      base:
        CODE_SIGN_ENTITLEMENTS: Dozer/SupportingFiles/Dozer.entitlements
        INFOPLIST_FILE: Dozer/SupportingFiles/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.mortennn.Dozer
        SWIFT_VERSION: 4.2
      configs:
        Debug: debug
        Release: release
    dependencies:
      - carthage: LaunchAtLogin
      - carthage: MASShortcut
      - carthage: Sparkle
      - carthage: AXSwift
      - framework: Frameworks/Crashlytics.framework
      - framework: Frameworks/Fabric.framework
  DozerTests:
    type: bundle.unit-test
    platform: [macOS]
    scheme: {}
    sources:
      - DozerTests
    settings:
      DEVELOPMENT_TEAM: DE6MHLRTVN
      base:
        SWIFT_VERSION: 4.2